
```{r}
sages_table1_juiced  <- readRDS(file=path(r.objects.folder.tidymodel,
                                          "035_sages_table1_juiced.rds"))


```

# Table 1

These are the variables used in the machine learning analyses.

**Note:** 2021-03-13 - Added the variables Length of Stay and Dichotomized cognitive decline to the descriptive table, but they are not included in the analysis. 
```{r}

sages_table1_juiced %>%
  select(-studyid, -testing_fct) %>%
  gtsummary::tbl_summary(by = testing_char,
                         statistic = list(all_continuous() ~ "{mean} ({sd})", 
                                          all_categorical() ~ "{n} / {N} ({p}%)"),
                         missing_text = "Missing",
                         type = list(vdcci ~ "continuous"),
                         digits = list(vars(lab.bun.cre.ratio, 
                                            vdlab09a_imp, 
                                            vdlab03a_imp) ~ c(1, 2))) %>%
  # add_stat_label() %>%
  add_overall() %>%
  as_gt() %>%
  cols_move_to_end(columns = c(5, 4)) %>%
  tab_row_group(group = "Insurance Type", rows = 79:82) %>%
  tab_row_group(group = "Lab values (10%)", rows = 65:78) %>%
  tab_row_group(group = "Lab values (Raw)", rows = 50:64) %>%
  tab_row_group(group = "Surgery", rows = 46:49) %>%
  tab_row_group(group = "Comorbidities", rows = 32:45) %>%
  tab_row_group(group = "Health status", rows = 14:31) %>%
  tab_row_group(group = "Health behaviors", rows = 10:13) %>%
  tab_row_group(group = "Demographics", rows = 3:9) %>%
  tab_row_group(group = "Outcome", rows = 1:2) %>%
  tab_options(table.font.size = pct(80))
  


```

